CREATE TABLE applications (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    institution_name VARCHAR(255) NOT NULL,

    application_number VARCHAR(255) NOT NULL UNIQUE,

    status VARCHAR(50) NOT NULL,

    applicant_id BIGINT,

    reviewer_id BIGINT,

    approver_id BIGINT,

    submitted_at TIMESTAMP NOT NULL,

    version BIGINT,

    CONSTRAINT fk_applicant
        FOREIGN KEY (applicant_id)
        REFERENCES users(id),

    CONSTRAINT fk_reviewer
        FOREIGN KEY (reviewer_id)
        REFERENCES users(id),

    CONSTRAINT fk_approver
        FOREIGN KEY (approver_id)
        REFERENCES users(id)
);