CREATE TABLE audit_logs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    application_id BIGINT NOT NULL,

    actor_email VARCHAR(255) NOT NULL,

    action VARCHAR(255) NOT NULL,

    previous_state VARCHAR(100) NOT NULL,

    new_state VARCHAR(100) NOT NULL,

    timestamp TIMESTAMP NOT NULL
);