CREATE TABLE application_documents (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    original_file_name VARCHAR(255) NOT NULL,

    stored_file_name VARCHAR(255) NOT NULL,

    content_type VARCHAR(255) NOT NULL,

    file_size BIGINT NOT NULL,

    version INTEGER NOT NULL,

    uploaded_at TIMESTAMP NOT NULL,

    uploaded_by BIGINT,

    application_id BIGINT,

    CONSTRAINT fk_document_user
        FOREIGN KEY (uploaded_by)
        REFERENCES users(id),

    CONSTRAINT fk_document_application
        FOREIGN KEY (application_id)
        REFERENCES applications(id)
);